<?= $this->extend('main') ?>
<?= $this->section('content') ?>
<?php $canManage=!empty($initial['can_manage']); $canDelete=!empty($initial['can_delete']); $canExport=!empty($initial['can_export']); $opts=$initial['options']??[]; ?>
<div id="ptspLayananApp" data-base-url="<?= esc(base_url()) ?>" data-manage="<?= $canManage?'1':'0' ?>" data-delete="<?= $canDelete?'1':'0' ?>">
<div class="sisfour-page-header"><div class="sisfour-page-header__copy"><h4 class="fw-bold mb-1">Layanan PTSP</h4><p class="text-muted mb-0">Administrasi pengajuan layanan berdasarkan Tahun Ajaran.</p></div><div class="sisfour-page-actions d-flex flex-wrap gap-2"><?php if($canManage): ?><button id="btnLayananBaru" class="btn btn-primary sisfour-touch-target" type="button"><i class="bx bx-plus me-1"></i>Tambah Internal</button><?php endif; ?></div></div>
<?php if(empty($initial['success'])): ?><div class="alert alert-danger"><?= esc($initial['message']??'Data tidak dapat dibuka.') ?></div><?php else: ?>
<div class="card sisfour-filter-card mb-4"><div class="card-body"><div class="row g-3 align-items-end">
<div class="col-12 col-md-3"><label class="form-label">Tahun Ajaran</label><select id="layananTahun" class="form-select"><?php foreach(($initial['tahun_options']??[]) as $ta): ?><option value="<?= (int)$ta['id'] ?>" <?= (int)($initial['tahun_dipilih']['id']??0)===(int)$ta['id']?'selected':'' ?>><?= esc($ta['nama_tahun'].' - '.$ta['semester'].((int)$ta['status_aktif']===1?' (Aktif)':'')) ?></option><?php endforeach; ?></select></div>
<div class="col-6 col-md-2"><label class="form-label">Status</label><select id="layananStatus" class="form-select"><option value="">Semua</option><?php foreach(($opts['status']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div>
<div class="col-6 col-md-3"><label class="form-label">Kategori</label><select id="layananKategori" class="form-select"><option value="">Semua</option><?php foreach(($opts['kategori']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div>
<div class="col-12 col-md-4"><label class="form-label">Pencarian</label><input id="layananSearch" class="form-control" placeholder="Nama / WhatsApp / keterangan"></div>
<div class="col-12"><div class="sisfour-filter-actions justify-content-md-end"><button id="btnLayananReset" class="btn btn-outline-secondary sisfour-touch-target--compact" type="button">Reset</button><button id="btnLayananCari" class="btn btn-primary sisfour-primary-action" type="button">Tampilkan</button></div></div>
</div></div></div>
<div id="layananAlert" class="alert d-none"></div>
<div class="card sisfour-table-card"><div class="card-header sisfour-section-heading d-flex justify-content-between align-items-center flex-wrap gap-2"><h5 class="mb-0">Daftar Pengajuan</h5><?php if($canExport): ?><a id="btnLayananExport" class="btn btn-sm btn-outline-primary sisfour-touch-target--compact" href="#">Export XLSX</a><?php endif; ?></div><div id="layananMobile" class="d-md-none list-group list-group-flush"></div><div class="d-none d-md-block"><table class="table table-hover align-middle mb-0"><thead><tr><th>Waktu</th><th>Pemohon</th><th>Layanan</th><th>Status</th><th>Petugas</th><?php if($canManage||$canDelete): ?><th>Aksi</th><?php endif; ?></tr></thead><tbody id="layananBody"></tbody></table></div><div class="card-footer"><div id="layananPager"></div></div></div>
<?php if($canManage): ?><div class="modal fade" id="modalLayananBaru" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-fullscreen-sm-down"><form id="formLayananBaru" class="modal-content"><div class="modal-header"><h5 class="modal-title">Tambah Layanan Internal</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama Lengkap</label><input name="nama_lengkap" class="form-control" required></div><div class="col-md-6"><label class="form-label">Kategori</label><select name="kategori_pemohon" class="form-select" required><option value="">Pilih</option><?php foreach(($opts['kategori']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input name="nomor_whatsapp" class="form-control" required></div><div class="col-md-6"><label class="form-label">Jenis Layanan</label><select name="jenis_layanan" class="form-select" required><option value="">Pilih</option><?php foreach(($opts['jenis_layanan']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Tujuan / Keterangan</label><textarea name="tujuan_keterangan" class="form-control" rows="4" required></textarea></div></div></div><div class="modal-footer sisfour-modal-actions"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Batal</button><button class="btn btn-primary" type="submit">Simpan</button></div></form></div></div><?php endif; ?>
<?php endif; ?></div>
<?= $this->endSection() ?>
