<?= $this->extend('main') ?>
<?= $this->section('content') ?>
<?php $canManage=!empty($initial['can_manage']); $canDelete=!empty($initial['can_delete']); $canExport=!empty($initial['can_export']); $opts=$initial['options']??[]; ?>
<div id="ptspPengaduanApp" data-base-url="<?= esc(base_url()) ?>" data-manage="<?= $canManage?'1':'0' ?>" data-delete="<?= $canDelete?'1':'0' ?>">
<div class="sisfour-page-header"><div class="sisfour-page-header__copy"><h4 class="fw-bold mb-1">Pengaduan PTSP</h4><p class="text-muted mb-0">Pengaduan publik anonim; data internal hanya untuk role yang diotorisasi.</p></div></div>
<?php if(empty($initial['success'])): ?><div class="alert alert-danger"><?= esc($initial['message']??'Data tidak dapat dibuka.') ?></div><?php else: ?>
<div class="card sisfour-filter-card mb-4"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-12 col-md-3"><label class="form-label">Tahun Ajaran</label><select id="pengaduanTahun" class="form-select"><?php foreach(($initial['tahun_options']??[]) as $ta): ?><option value="<?= (int)$ta['id'] ?>" <?= (int)($initial['tahun_dipilih']['id']??0)===(int)$ta['id']?'selected':'' ?>><?= esc($ta['nama_tahun'].' - '.$ta['semester'].((int)$ta['status_aktif']===1?' (Aktif)':'')) ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-2"><label class="form-label">Status</label><select id="pengaduanStatus" class="form-select"><option value="">Semua</option><?php foreach(($opts['status']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-3"><label class="form-label">Klasifikasi</label><select id="pengaduanKlasifikasi" class="form-select"><option value="">Semua</option><?php foreach(($opts['klasifikasi']??[]) as $o): ?><option><?= esc($o) ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-4"><label class="form-label">Pencarian</label><input id="pengaduanSearch" class="form-control" placeholder="Judul / isi"></div><div class="col-6 col-md-3"><label class="form-label">Dari</label><input id="pengaduanMulai" type="date" class="form-control"></div><div class="col-6 col-md-3"><label class="form-label">Sampai</label><input id="pengaduanSelesai" type="date" class="form-control"></div><div class="col-12 col-md-6"><div class="sisfour-filter-actions justify-content-md-end"><button id="btnPengaduanReset" class="btn btn-outline-secondary sisfour-touch-target--compact" type="button">Reset</button><button id="btnPengaduanCari" class="btn btn-primary sisfour-primary-action" type="button">Tampilkan</button></div></div></div></div></div>
<div id="pengaduanAlert" class="alert d-none"></div><div class="card sisfour-table-card"><div class="card-header sisfour-section-heading d-flex justify-content-between align-items-center flex-wrap gap-2"><h5 class="mb-0">Daftar Pengaduan</h5><?php if($canExport): ?><a id="btnPengaduanExport" class="btn btn-sm btn-outline-primary sisfour-touch-target--compact" href="#">Export XLSX</a><?php endif; ?></div><div id="pengaduanMobile" class="d-md-none list-group list-group-flush"></div><div class="d-none d-md-block"><table class="table table-hover align-middle mb-0"><thead><tr><th>Waktu</th><th>Laporan</th><th>Klasifikasi</th><th>Status</th><th>Lampiran</th><?php if($canManage||$canDelete): ?><th>Aksi</th><?php endif; ?></tr></thead><tbody id="pengaduanBody"></tbody></table></div><div class="card-footer"><div id="pengaduanPager"></div></div></div>
<?php endif; ?></div>
<?= $this->endSection() ?>
