<?= $this->extend('main') ?>
<?= $this->section('content') ?>
<?php $options=$initial['options']??[]; ?>
<div id="bkKonselingKelompokApp" data-base-url="<?= esc(base_url()) ?>" data-options="<?= esc(json_encode($options, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'attr') ?>" data-can-manage="<?= !empty($initial['can_manage'])?'1':'0' ?>">
  <div class="sisfour-page-header"><div class="sisfour-page-header__copy"><h4 class="fw-bold mb-1">Konseling Kelompok</h4><p class="text-muted mb-0">Satu sesi rahasia untuk beberapa siswa dengan anggota dan tindak lanjut terpisah dari Konseling Individu.</p></div>
    <div class="sisfour-page-actions"><a class="btn btn-outline-secondary" href="<?= esc(base_url('bk/konseling')) ?>"><i class="bx bx-left-arrow-alt me-1"></i> Konseling Individu</a><?php if(!empty($initial['can_manage'])):?><button id="btnKonselingKelompokBaru" class="btn btn-primary" type="button"><i class="bx bx-group me-1"></i> Konseling Kelompok Baru</button><?php endif;?></div></div>
  <?php if(empty($initial['success'])):?><div class="alert alert-danger"><?= esc($initial['message']??'Konseling Kelompok tidak dapat dibuka.') ?></div><?php else:?>
    <div class="alert alert-warning"><i class="bx bx-lock-alt me-1"></i><strong>Data rahasia.</strong> Anggota kelompok tidak tersedia untuk Pimpinan/Guru/Wali/Siswa/Kesehatan/PTSP.</div>
    <div class="card sisfour-filter-card mb-4"><div class="card-body"><form method="get" class="row g-3 align-items-end">
      <div class="col-md-3"><label class="form-label">Tahun Ajaran</label><select name="id_tahun" class="form-select" data-searchable-off="1"><?php foreach(($initial['tahun_options']??[]) as $ta):?><option value="<?= (int)$ta['id'] ?>" <?= (int)($initial['tahun_dipilih']['id']??0)===(int)$ta['id']?'selected':'' ?>><?= esc($ta['nama_tahun'].' - '.$ta['semester'].((int)($ta['status_aktif']??0)===1?' (Aktif)':'')) ?></option><?php endforeach;?></select></div>
      <div class="col-md-3"><label class="form-label">Pencarian</label><input class="form-control" name="search" value="<?= esc((string)(service('request')->getGet('search')??'')) ?>" placeholder="Topik / uraian"></div>
      <div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua</option><option>Proses</option><option>Selesai</option></select></div>
      <div class="col-md-2"><label class="form-label">Bidang</label><select name="bidang" class="form-select"><option value="">Semua</option><?php foreach(($options['bidang']??[]) as $b):?><option value="<?= esc($b,'attr') ?>"><?= esc($b) ?></option><?php endforeach;?></select></div>
      <div class="col-md-2"><button class="btn btn-primary w-100" type="submit">Tampilkan</button></div>
    </form></div></div>
    <div id="groupKonselingAlert" class="alert d-none"></div>
    <div class="card sisfour-table-card"><div class="card-header d-flex justify-content-between"><h5 class="mb-0">Riwayat Konseling Kelompok</h5><span class="small text-muted"><?= number_format((int)($initial['total']??0),0,',','.') ?> sesi</span></div>
      <div class="d-md-none list-group list-group-flush"><?php foreach(($initial['rows']??[]) as $r):?><button type="button" class="list-group-item list-group-item-action btn-group-konseling-detail text-start" data-id="<?= (int)$r['id'] ?>"><div class="d-flex justify-content-between gap-2"><strong><?= esc($r['topik']??'-') ?></strong><span class="badge bg-label-primary"><?= (int)($r['jumlah_anggota']??0) ?> siswa</span></div><div class="small text-muted"><?= esc($r['tanggal']??'-') ?> · <?= esc($r['bidang']??'-') ?> · <?= esc($r['status']??'-') ?></div></button><?php endforeach;?></div>
      <div class="d-none d-md-block table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Tanggal</th><th>Anggota</th><th>Layanan</th><th>Bidang / Topik</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody><?php if(($initial['rows']??[])===[]):?><tr><td colspan="6" class="text-center text-muted py-4">Belum ada Konseling Kelompok.</td></tr><?php endif;?><?php foreach(($initial['rows']??[]) as $r):?><tr><td><?= esc($r['tanggal']??'-') ?></td><td><?= (int)($r['jumlah_anggota']??0) ?> siswa</td><td><?= esc($r['bentuk_layanan']??'-') ?></td><td><?= esc(($r['bidang']??'-').' · '.($r['topik']??'-')) ?></td><td><span class="badge bg-label-<?= ($r['status']??'')==='Selesai'?'success':'warning' ?>"><?= esc($r['status']??'-') ?></span></td><td class="text-end"><button type="button" class="btn btn-sm btn-outline-primary btn-group-konseling-detail" data-id="<?= (int)$r['id'] ?>">Detail</button></td></tr><?php endforeach;?></tbody></table></div>
    </div>

    <?php if(!empty($initial['can_manage'])):?>
    <div class="modal fade" id="modalKonselingKelompokBaru" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-fullscreen-sm-down"><form id="formKonselingKelompok" class="modal-content">
      <div class="modal-header"><div><h5 class="modal-title mb-1">Konseling Kelompok — Tahap 1</h5><small class="text-muted">Pilih minimal 2 siswa dari Tahun Ajaran aktif.</small></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Tutup"></button></div>
      <div class="modal-body">
        <div class="mb-3"><label class="form-label">Cari Siswa</label><div class="input-group"><select id="groupKonselingSiswa" class="form-select" data-searchable-remote="<?= esc(base_url('ui/search/siswa')) ?>" data-searchable-context="bk_konseling" data-searchable-min-chars="2"><option value="">Cari nama / NISN</option></select><button id="btnTambahGroupKonselingSiswa" class="btn btn-outline-primary" type="button">Tambah</button></div></div>
        <div class="border rounded p-2 mb-3"><div class="small fw-semibold mb-2">Anggota <span id="groupKonselingCount" class="badge bg-label-primary">0</span></div><div id="groupKonselingMembers"><span class="small text-muted">Belum ada siswa dipilih.</span></div></div>
        <div class="row g-3"><div class="col-md-4"><label class="form-label">Tanggal</label><input class="form-control" type="date" name="tanggal" required></div><div class="col-md-2"><label class="form-label">Pertemuan ke-</label><input class="form-control" type="number" min="1" max="99" name="pertemuan_ke" value="1" required></div>
        <div class="col-md-6"><label class="form-label">Bentuk Layanan</label><select class="form-select" name="bentuk_layanan" required><option value="">Pilih</option><?php foreach(($options['bentuk_layanan']??[]) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div>
        <div class="col-md-6"><label class="form-label">Cara Hadir</label><select class="form-select" name="cara_hadir" required><option value="">Pilih</option><?php foreach(($options['cara_hadir']??[]) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div>
        <div class="col-md-3"><label class="form-label">Bidang</label><select id="groupKonselingBidang" class="form-select" name="bidang" required><option value="">Pilih</option><?php foreach(($options['bidang']??[]) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div>
        <div class="col-md-3"><label class="form-label">Topik</label><select id="groupKonselingTopik" class="form-select" name="topik" required><option value="">Pilih bidang dahulu</option></select></div></div>
      </div><div class="modal-footer sisfour-modal-actions"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Simpan Tahap 1</button></div>
    </form></div></div>
    <?php endif;?>

    <div class="modal fade" id="modalKonselingKelompokDetail" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable modal-fullscreen-sm-down"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Detail Konseling Kelompok</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="groupKonselingDetailLoading">Memuat data...</div><div id="groupKonselingDetailContent" class="d-none">
      <div class="mb-3"><strong id="groupKonselingDetailTitle">-</strong><div class="small text-muted" id="groupKonselingDetailMeta"></div></div>
      <h6>Anggota</h6><div id="groupKonselingDetailMembers" class="list-group mb-4"></div>
      <?php if(!empty($initial['can_manage'])):?><form id="formKonselingKelompokHasil" class="border rounded p-3 mb-4"><input type="hidden" name="id"><h6>Hasil Pertemuan Awal</h6><div class="row g-3"><div class="col-12"><label class="form-label">Uraian Masalah</label><textarea class="form-control" name="uraian_masalah" rows="3"></textarea></div><div class="col-12"><label class="form-label">Hasil / Kesepakatan</label><textarea class="form-control" name="hasil_kesepakatan" rows="3"></textarea></div><div class="col-md-5"><label class="form-label">Rencana Berikutnya</label><select class="form-select" name="rencana_berikutnya"><option value="">Tidak ada</option><?php foreach(($options['rencana']??[]) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Tanggal Berikutnya</label><input class="form-control" type="date" name="tanggal_berikutnya"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(($options['status']??['Proses','Selesai']) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div></div><div class="text-end mt-3"><button class="btn btn-primary" type="submit">Simpan Hasil</button></div></form><?php endif;?>
      <h6>Riwayat Tindak Lanjut</h6><div id="groupKonselingDetailFollow" class="list-group mb-4"></div>
      <?php if(!empty($initial['can_manage'])):?><form id="formKonselingKelompokFollow" class="border rounded p-3"><input type="hidden" name="id_konseling_kelompok"><h6>Tambah Tindak Lanjut</h6><div class="row g-3"><div class="col-md-3"><label class="form-label">Tanggal</label><input class="form-control" type="date" name="tanggal" required></div><div class="col-md-9"><label class="form-label">Perkembangan</label><textarea class="form-control" name="perkembangan" rows="2" required></textarea></div><div class="col-12"><label class="form-label">Hasil / Kesepakatan</label><textarea class="form-control" name="hasil_kesepakatan" rows="2"></textarea></div><div class="col-md-5"><label class="form-label">Rencana Berikutnya</label><select class="form-select" name="rencana_berikutnya"><option value="">Tidak ada</option><?php foreach(($options['rencana']??[]) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Tanggal Berikutnya</label><input class="form-control" type="date" name="tanggal_berikutnya"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(($options['status']??['Proses','Selesai']) as $v):?><option value="<?= esc($v,'attr') ?>"><?= esc($v) ?></option><?php endforeach;?></select></div></div><div class="text-end mt-3"><button class="btn btn-primary" type="submit">Tambah Tindak Lanjut</button></div></form><?php endif;?>
    </div></div></div></div></div>
  <?php endif;?>
</div>
<?= $this->endSection() ?>
